### ISSUE TITLE
Update with your own Google Analytics

### ISSUE THREAD

**Issue by imteekay** [gizemindefteri/gizemindefteri.github.io#1]
I noticed you use my website as a template. Can you update the [google analytics tracking code](https://github.com/gizemindefteri/gizemindefteri.github.io/blob/main/index.html#L62) with your own GA or just remove the GA code from the website?

**Comment by gizemindefteri** [comment]
Hey TK, thanks for pointing it out. I have fixed it and am very happy to learn this. 
Note: I wanted to get familiar with the workspace of a professional web developer. I am grateful to you for sharing these open-source also providing free tutorials.

**Comment by imteekay** [comment]
No problem!
Happy to help! 🎉 

I think you also need to replace the tracking code from this line as well: https://github.com/gizemindefteri/gizemindefteri.github.io/blob/main/index.html#L54

Or if you are not using google analytics, you can remove the entire gtm tag: https://github.com/gizemindefteri/gizemindefteri.github.io/blob/main/index.html#L52-L62

And I think you probably need to do for the other pages too. (Fotograflar, Quotes, etc).

**Comment by imteekay** [comment]
@gizemindefteri, create a PR (https://github.com/gizemindefteri/gizemindefteri.github.io/pull/2) to fix what I mentioned below. Let me know if everything is ok.

**Comment by gizemindefteri** [comment]
Everything looks fine. Sorry to busy you. I will be more careful.

**Comment by imteekay** [comment]
No worries! 😅 Happy new year! 🎉
